version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  preprocessing:
    build: ./preprocessing
    depends_on:
      - db
    volumes:
      - ./preprocessing/app.py:/app/app.py
      - ./data:/data
    env_file:
      - .env

  model:
    build: ./model
    depends_on:
      - db
      - preprocessing
      - mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./shared:/shared
    env_file:
      - .env

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - model
      - mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./shared:/shared
    env_file:
      - .env

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --artifacts-destination /mlflow/mlruns --host 0.0.0.0 --port 5000

volumes:
  pgdata:
  mlruns:
  shared: